### ISSUE TITLE
Grants Program

### ISSUE THREAD

**Issue by jacobcreech** [solana-developers/solana-grants#4]
The Grants Program will be the backend for the following:

- Grants Creation
- Grant funding
- Grant Matching
- Quadratic Matching

For the grant program, you will likely have at least the following account:

- Grant Info Account

Which will have at least the following information:

- Grant Title
- Grant Description
- Grant Image Link
- Grant Github Link
- Grant Amount
- Grant Creator

Things to consider:

- How do we verify this account is who they say they are? (Twitter verification? Github Verification?)
- How do I make sure this account is queryable without using getProgramAccounts?
- How do I keep track of all current grants? (Can do web2 solution)
- How do I make sure this grant account is as small as possible?
- How do I enable a user to create more than one grant without creating account collisions?
- How do I enable blocking controls on the front end if needed in the future(scam grants)?

**Comment by coszio** [comment]
## Design Prototype

After discussing with the teammates, we came up with this design for the Solana program that will manage the grants and transactions.

Right now we were thinking that the grant matching (or quadratic matching) can be represented in the same way as a normal donation; as a `GrantPayment`. It will just have the other account as the payer. Such logic can be implemented in the program.

![image](https://user-images.githubusercontent.com/62079184/174889369-0655d775-a643-40ae-acfa-01c9a590c7eb.png)

@jacobcreech What do you think? Do you have any recommendations?

**Comment by jacobcreech** [comment]
How does grant info own grant payment? How does that work?

How do you plan on deriving each account?

Who has authority to update GrantInfo or GrantPayment? Where is that authority stored/checked?

You have a bunch of `getX` instructions. I don't think programs return data today via executing transactions. You should have a plan on how to get the accounts via key derivation.

How do you plan on automating matching grants?

**Comment by coszio** [comment]
I'll just update this thread with the latest diagram, my understanding of the recent meetings we had.

![image](https://user-images.githubusercontent.com/62079184/177627665-f1e90f9a-4d03-4cef-a6c6-5df688b58582.png)
